### ISSUE TITLE
Please tag latest version as 1.4.0

### ISSUE THREAD

**Issue by tzneal** [paulmach/go.geojson#14]
Unfortunately go is strict regarding semver.  I just did a go get on this package and then checked your releases.  A plain go get downloaded v1.3.1 as it's the latest semver compliant tag (vn.n.n), and ignored v1.4 due to the missing last digit.  v1.4 should be tagged as v1.4.0 for go 1.11+ with module support to work.

See https://github.com/golang/go/issues/24476 for some comments where it doesn't appear that this will change, in particular: 

```
This should be fixed. I think vgo should just completely ignore non-canonical semver tags (v1 or v1.0 instead of v1.0.0) in repos.
```

**Comment by paulmach** [comment]
done
