### ISSUE TITLE
Bounding Box Computation PR

### ISSUE THREAD

**Issue by tbonfort** [paulmach/go.geojson#15]
Hi,
Would you accept a PR implementing the calculation of the bounding box for Geometry, Feature and FeatureCollection ?
regards,
Thomas

**Comment by paulmach** [comment]
This package is best for lightweight interaction with GeoJSON. If you want to actually do stuff with the geometry take a look at [orb/geojson](https://github.com/paulmach/orb/tree/master/geojson) which decodes the geometries into [orb](https://github.com/paulmach/orb) types which you can do all sorts of things with.
