### ISSUE TITLE
Geometry from WKT

### ISSUE THREAD

**Issue by josebalius** [paulmach/go.geojson#2]
Hi @paulmach 

Great library, i use it quite a bit and it works great. I have a question, let's say I have a bunch of records in WKT (some points, poly, lines, etc) and I would like build a geojson out of them. 

What would you say is the best way to extract the geometry from WKT in a way that this library will easily understand it? Do you have a recommendation?

Thanks again!

Jose

**Comment by paulmach** [comment]
Hum, I don't know of any libraries that parse WKT.  Maybe @twpayne has a recommendation?

**Comment by josebalius** [comment]
@paulmach I found https://github.com/paulsmith/gogeos (https://godoc.org/github.com/paulsmith/gogeos/geos#Geometry.Coords) but the `Coords()` method returns a single slice vs `[][][]float64` for a poly for example, which doesn't quite work for us.
