### ISSUE TITLE
Doc typos

### ISSUE THREAD

**Issue by razor-1** [paulmach/go.geojson#21]
Documentation for methods such as `PropertyMustInt` are copied from `bool` instead of referring to the correct types.

**Comment by paulmach** [comment]
can you point to a location? https://github.com/paulmach/go.geojson/blob/master/properties.go looks good to me

**Comment by razor-1** [comment]
I see what's going on: the latest tag that go mod picks up is v1.4.0.

In https://github.com/paulmach/go.geojson/blob/v1.4.0/properties.go the issue exists

If it's possible to publish v1.4.1 or similar, that would be great.

**Comment by paulmach** [comment]
done, published v1.5.0 with some other changes. See the release for more info

https://github.com/paulmach/go.geojson/releases/tag/v1.5.0
