### ISSUE TITLE
Allow creation of copies of Geometries, rather than references

### ISSUE THREAD

**Issue by reezer** [paulmach/go.geojson#6]
It would be really nice if one could easily create a copy of a Geometry without having to worry about any references. I see two ways to achieve this, either by modifying the constructors for new Geometries or by adding a `Copy()` method.

Currently `NewPolygonGeometry` for example takes the `polygon [][][]float64` and simply uses it. However that means if something modifies the passed polygon it will also modify the geometry.

For the reason I'd suggest to either create a copy using something like this whenever a new polygon is created

```
cp := make([][][]float64, len(polygon))
copy(cp, polygon)
```

An alternative would be to explicitly create a new copy of a geometry using a method in the form of `func (g *Geometry) Copy() *Geometry` (or Clone)  returning an exact copy, with now more references to the original.

The second option would I think would both be cleaner as well as allowing people to choose whether they really want to allocate a new slice.

**Comment by paulmach** [comment]
👍  good idea.

I also like the second option. I'm also like the name `Clone` since in my mind that implies a deep copy.

Are you interested in implementing this?

**Comment by paulmach** [comment]
I know this is super old but I wanted to close this with a solution :)

To do "things" with geometries like Clone them, consider using https://github.com/paulmach/orb

Using orb you'd take your raw geojson data and do something like: 
```
package main

import (
	"fmt"

	"github.com/paulmach/orb"
	"github.com/paulmach/orb/geojson"
	"github.com/paulmach/orb/planar"
)

func main() {
	rawGeoJSONFeature := []byte{}

	feature, err := geojson.UnmarshalFeature(rawGeoJSONFeature)
	if err != nil {
		panic(err)
	}

	// generally
	theClone := orb.Clone(feature.Geometry)

	// if you know the type of the geometry and want to work with it directly
	polygon, ok := feature.Geometry.(orb.Polygon)
	if !ok {
		panic(fmt.Sprintf("geometry not a polygon, it's a %s", feature.Geometry.GeoJSONType()))
	}

	theClone = polygon.Clone()
}
```
