### ISSUE TITLE
IsIn function on Geometric

### ISSUE THREAD

**Issue by genofire** [paulmach/go.geojson#8]
It would be cool, to validate easy if a point is in a area/Polygon.

**Comment by paulmach** [comment]
I know this is super old, but I'm going to close it with some hopefully helpful info for completeness.

To do a "point in polygon" thing, consider using https://github.com/paulmach/orb

Using orb you'd take your raw geojson data and do something like: 
```
package main

import (
	"fmt"

	"github.com/paulmach/orb"
	"github.com/paulmach/orb/geojson"
	"github.com/paulmach/orb/planar"
)

func main() {
	point := orb.Point{1, 2} // some point to test
	rawGeoJSONFeature := []byte{}

	feature, err := geojson.UnmarshalFeature(rawGeoJSONFeature)
	if err != nil {
		panic(err)
	}

	polygon, ok := feature.Geometry.(orb.Polygon)
	if !ok {
		panic(fmt.Sprintf("geometry not a polygon, it's a %s", feature.Geometry.GeoJSONType()))
	}

	if planar.PolygonContains(polygon, point) {
		fmt.Printf("YES")
	} else {
		fmt.Printf("NO")
	}
}
```

**Comment by winglq** [comment]
How could I convert Geometry to orb.Polygon? Thanks.

**Comment by paulmach** [comment]
@winglq do not use this library use [orb/geojson](https://godoc.org/github.com/paulmach/orb/geojson).

Then do a type assertion something like:
```
polygon, ok := feature.Geometry.(orb.Polygon)
if !ok {
	panic(fmt.Sprintf("geometry not a polygon, it's a %s", feature.Geometry.GeoJSONType()))
}
```
