### ISSUE TITLE
Struct to contain feature collection and other custom data

### ISSUE THREAD

**Issue by TheMangoTrain** [paulmach/go.geojson#9]
Hello,

go.geojson is functional for me, however I'd like to add additional custom JSON data to the output, seperate from the FeatureCollection. I have both geojson and event data (for the locations) successfully outputting via REST API as two different routes. However I'd like to combine them so that the JSON has two main children: a 'FeatureCollection' and 'Events' containing my custom events data.

My first approach has been to create a new struct to encapsulate them both, like so:
```
// GeoLocationsEvents type
type GeoLocationsEvents struct {
	Locations FeatureCollection `schema:"locations"`
	Events []Event `schema:"events"`
}
```

However I get a type incompatibility error when it comes time to make use of the fc object that go.geojson is outputting.

This is my router function:
```
func (a *App) getLocationsEventsGeoJSON(w http.ResponseWriter, r *http.Request) {

 // This successfully returns a complete FeatureCollection (using go.geojson) and a complete Events object.
    fc, events, err := getLocationsEvents(a.DB, start, count)
    if err != nil {
        respondWithError(w, http.StatusInternalServerError, err.Error())
        return
    }


// Now, I attempt to merge the two using my new struct.
// My intention is to pass it to a final function which marshals the json.
	var locationsEvents GeoLocationsEvents

// THIS CAUSES AN ERROR: cannot use fc (type *geojson.FeatureCollection) as type *FeatureCollection in assignment
	locationsEvents.Locations = fc
	locationsEvents.Events = events

      // The final function call before outputting to client. If I test with fc or events directly, they both work spitting JSON to the browser. However I want them to be combined.
       respondWithGeoJSON(w, http.StatusOK, locationsEvents)
}
```

```
func getLocationsEvents(db *sql.DB, start, count int) ([]Location, []Event, *geojson.FeatureCollection, error) {

	var events = []Event{}
	elements := map[int]int{}
	fc := geojson.NewFeatureCollection()

// and much more... excluded from post

}
```

**Comment by paulmach** [comment]
I think, in your struct, you need to reference 'FeatureCollection' using the full name like so:
```
type GeoLocationsEvents struct {
	Locations *geojson.FeatureCollection `schema:"locations"`
	Events []Event `schema:"events"`
}
```

This is essentially what the error message says `cannot use fc (type *geojson.FeatureCollection) as type *FeatureCollection in assignment`

fc is of type `*geojson.FeatureCollection`  but the struct is defined as `*FeatureCollection` so you can't assign them. In this case the struct definition needs to be updated.

**Comment by TheMangoTrain** [comment]
Yes that was it, thanks so much!

I tried that previously, however forgot about to add the import to my structs file.
```
import (
	"github.com/paulmach/go.geojson"
)
```
Many thanks!
